version: "3.9"
volumes:
    cmdbuild-db:
      external: true
    cmdbuild-tomcat:
      external: true
    pgadmin-data:
      external: true

services:
    cmdbuild_db:
        build: ./postgres/
        image: olehkondratov/cmdbuild:db-12
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    #    env_file:
    #      - config.env
        restart: always
        mem_limit: 1000m
        mem_reservation: 300m

    cmdbuild_app:
        build: .
        image: olehkondratov/ready2use-2.3-3.4.1:latest
        container_name: cmdbuild_app
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild_db
            - POSTGRES_DB=cmdbuild_r2u2
            - CMDBUILD_DUMP=demo.dump.xz
    #       - CMDBUILD_DUMP=archiwum.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m
    #    env_file:
    #      - config.env
        mem_limit: 4000m
        mem_reservation: 2000m

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - "80:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@exea.pl
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
    #    PGADMIN_CONFIG_LOGIN_BANNER: "Authorised users only!"
        PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10 
      volumes:
        - pgadmin-data:/var/lib/pgadmin

    nginx:
      container_name: nginx
      links:
        - pgadmin:pgadmin
      image: nginx:1.23
      ports:
        - "5050:80"
      volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      restart: always