version: "3.9"
volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: olehkondratov/cmdbuild:db-12
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - 5432:5432
        env_file:
          - config.env
        restart: always
        mem_limit: 1000m
        mem_reservation: 300m

    cmdbuild_app:
        image: olehkondratov/ready2use-2.3-3.4.1:latest
        container_name: cmdbuild_app
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        env_file:
          - config.env
        mem_limit: 4000m
        mem_reservation: 2000m